name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt -- --check

  lint:
    name: Run Linter (clippy)
    runs-on: ubuntu-latest
    needs: format
    
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: cargo clippy -- -D warnings

  build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      # Sequential testing required since events are processed by global publisher
      run: cargo test --verbose -- --test-threads 1
